### ISSUE TITLE
[BUG] Mythical cobblemon don't spawn with right Textures 

### ISSUE THREAD

**Issue by PassyFox** [brysondev/Legendary-Encounters#2]
**Describe the bug**
Some mythical cobblemon (e.g. Meloetta, Victini, Jirachi, Marshadow) don't spawn with their intended textures 

** To Reproduce **
Just summon them in via /spawnpokemon

** Expected behavior **
Normaly they would give their regular textures

** Screenshots **
see the screenshot how they are being displayed now
![2024-05-29_16 11 02](https://github.com/brysondev/Legendary-Encounters/assets/20614880/d0a37e02-1f27-4aed-afc3-3410aa72f273)

** Official Cobblemon Modpack **
Version 1.5.2 (via Modrinth)

** Additional context **
i think the original cobblemon mod might interfere with your textures but i don't have the appropriate knowledge to confirm, since other mythical or legendary pokemon can be spawned like celebi or arceus but will have the same textures as the ones from you.

**Comment by brysondev** [comment]
Cobblemon devs have not added any of those legendary models into their mod or modpack yet. So trying to spawn them results in that placeholder.

See a fresh install of the latest modpack:
![image](https://github.com/brysondev/Legendary-Encounters/assets/13501615/d3acabe5-1320-4263-bb3b-0a0230cda94a)

Closing.

**Comment by PassyFox** [comment]
But when i look on modrinth you have an image their with a victini in it with your own mod, as your own documentation states that these pokemon will spawn in the wild. But even then encountering them will result in placeholder skins. Thus are you implying that the mod is only there for the sake of the spawn mechanics and not for the textures of said pokemon?

**Comment by brysondev** [comment]
Outright lying when this repo is fully public with all files being viewable, and trying to have discussion with me over how a datapack that does nothing but reintroduce scripting "legendary encounters" (as the name implies) is insane, this is now locked. Please review [GitHub Community Guidelines](https://docs.github.com/articles/github-community-guidelines).
